#Spring
application.recommendations-db.url=jdbc:h2:file:./transaction
spring.datasource.url= jdbc:postgresql://localhost:5432/rules
spring.datasource.username= root
spring.datasource.password= 1111
spring.liquibase.change-log= classpath:liquibase/changelog-master.yml


# Hibernate ddl auto (create, create-drop, validate, update)

spring.jpa.hibernate.ddl-auto= validate
spring.jpa.show-sql=true
server.port=8080

spring.cache.cache-names=Recommendations
spring.cache.caffeine.spec=initialCapacity=50,maximumSize=10,expireAfterAccess=300s